[package]
name = "advent-of-code-2025"
version = "0.1.0"
authors = ["Yoeri Otten <yoeri@otten.dev>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
rand = "0.8.5"
regex = "1.11.1"
